### ISSUE TITLE
Add the latest cards

### ISSUE THREAD

**Issue by GuiSim** [pedrovhb/lor_sheet#1]
Hey! As you know, a bunch of new cards were added. Could your site support them and the new Bilgewater region?

Thank you!

**Comment by pedrovhb** [comment]
Updated to add the new cards and made a few improvements to non-Firefox browser support.

It's also easier for me to update card data now so it'll hopefully be updated quicker in the future :)

**Comment by GuiSim** [comment]
Thank you so much @pedrovhb ! 

Out of curiosity, what drove you to put cards like Twisted Fate and Citrus Courrier in Bilgewater but not Rhasa or Ledros in Shadow Isle? I'm just wondering what are the "rules" for a card to be included by default.

**Comment by pedrovhb** [comment]
@GuiSim you're welcome!

Honestly I just didn't really think about it too much. Rhasa definitely should be included. I can see the case for Ledros coming out and putting you in range for a lethal you didn't expect, so that would be valid too.

I'm open to taking card inclusion/exclusion suggestions here and on Reddit. I realize that as is, it's only slightly more consistent than Riot's wording on cards :)

**Comment by GuiSim** [comment]
My 2¢ would be to add all units that have an on-play effect and simply add a quick filter (similar to burst/fast VS slow/units) to filter out units.

Otherwise you'll end up with a tough subjective approach. I guess you could ask "Should I be wary of my opponent playing this card?"

**Comment by GuiSim** [comment]
Did Bilgewater disappear?

@pedrovhb I can't see them on http://lor.pedrovhb.com/ anymore

**Comment by pedrovhb** [comment]
@GuiSim should still be there. Try to clear you browser's cache, especially if it's one you had only used before the update. Sometimes the only thing that works for me is opening up dev tools with F12, checking "Disable cache" under the Network tab and reloading, or visiting the page in a private tab.
